### ISSUE TITLE
Architecture-codereview: comments

### ISSUE THREAD

**Issue by parvizi** [AgoraCloud/server#56]
You have great progress. Your code and documents are clear; although, I am not a JS expert. I can add these two comments:
1- It is not clear how you manage deployment. Do you compile and deploy instances of codes in a separate docker? 
2- You can automate testing in CI/CD as well.

**Comment by saidghamra** [comment]
Hi @parvizi,

1- We use the Kubernetes API (through the [Kubernetes client package](https://github.com/kubernetes-client/javascript)) to communicate with the Kubernetes cluster and create all the necessary Kubernetes resources (such as pvc's, deployments, configmaps, ...) for [code-server containers](https://hub.docker.com/r/linuxserver/code-server). For more details, you can see [this event handler](https://github.com/AgoraCloud/server/blob/b4c588a495fa30e2b5cd4c867c8a254d6937920a/src/modules/kubernetes/kubernetes.service.ts#L240) which handles deployment creation. We simply spin up and spin down code-server containers in different namespaces in the Kubernetes cluster.

2- Our [CI/CD pipelines](https://github.com/AgoraCloud/server/blob/b4c588a495fa30e2b5cd4c867c8a254d6937920a/.github/workflows/pr_checks.yaml#L21) automatically run tests on pull requests.

**Comment by saidghamra** [comment]
Hi @parvizi,

I might have misunderstood your first question. If you are asking about how we dockerize the server and ui, we have Dockerfiles in both repositories that run on each push to any branch and publish the image to Docker Hub. We then use these Docker images in our [helm-chart](https://github.com/AgoraCloud/server/blob/b4c588a495fa30e2b5cd4c867c8a254d6937920a/helm-chart/values.yaml#L4) to deploy AgoraCloud on a cluster.

- [Server Images on Docker Hub](https://hub.docker.com/repository/docker/agoracloud/server/tags?page=1&ordering=last_updated)
- [Server Dockerfile](https://github.com/AgoraCloud/server/blob/main/Dockerfile)
- [UI Images on Docker Hub](https://hub.docker.com/repository/docker/agoracloud/ui/tags?page=1&ordering=last_updated)
- [UI Dockerfile](https://github.com/AgoraCloud/ui/blob/main/Dockerfile)
