### ISSUE TITLE
Ensure a Workspace Has at Least One Admin Member After a User Is Removed

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/server#70]
When I added functionality to add and remove members from a workspace, I forgot to account for the case when a workspace will have no admin members left if an admin member is removed.

**Comment by MarcDAFrame** [comment]
I think the functionality of this should be, it throws an error if you attempt to remove yourself and you are the only admin.

The error message says, "make someone else an admin before you remove yourself"

This way it doesn't just randomly decide who will be the admin.

Additionally, will removing yourself from a workspace where you're the only person effectively be the same as just deleting the workspace?
